name: eyecare_mac
description: "EyeCare Mac - A macOS menu bar app for eye strain prevention using
  the 20-20-20 rule."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  tray_manager: ^0.5.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
